version: "3.3"

services:
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql
            - ./logs:/var/log/mysql
        ports:
            - ${PORT}:${PORT}
        expose:
            - "${PORT}" 
